apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: {{APP_NAME}}
spec:
  serviceName: {{APP_NAME}}
  replicas: {{REPLICAS}}
  template:
    metadata:
      labels:
        app: {{APP_NAME}}
      annotations:
        pod.alpha.kubernetes.io/initialized: "true"
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: {{APP_NAME}}
        image: {{IMAGE_NAME}}
        imagePullPolicy: Always
        ports:
        - containerPort: 8125
          name: incoming-udp
          protocol: UDP
        - containerPort: 8126
          name: admin
          protocol: TCP
