apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: {{APP_NAME}}
spec:
  serviceName: {{APP_NAME}}
  replicas: {{REPLICAS}}
  template:
    metadata:
      labels:
        app: {{APP_NAME}}
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: {{APP_NAME}}
        image: {{IMAGE_NAME}}
        imagePullPolicy: Always
        env:
          - name: CURATOR_RETENTION
            value: "{{CURATOR_RETENTION}}"
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        - containerPort: 2004
          name: pickle
          protocol: TCP
        resources:
          limits:
            cpu: 2000m
            memory: 4Gi
          requests:
            cpu: 1000m
            memory: 2Gi
        volumeMounts:
        - name: data
          mountPath: /opt/graphite/storage/whisper
  volumeClaimTemplates:
  - metadata:
      name: data
      annotations:
        volume.beta.kubernetes.io/storage-class: graphite-ceph-rbd
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: "{{DISK_SIZE}}"
